---
title: "Lab 5 Fun Times"
author: "Annette Hilton"
date: "10/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objectives: 

- Getting counts for different groups
- Use {lubridate} to parse dates
- Find confidence intervals and do t-tests with t.test() 
- Heatmap with geom_tile()


```{r, include = FALSE}
 # Attach packages

library(tidyverse)
library(here)
library(janitor)

```

```{r}
# Import lobster data 
# Put in clarification for NA values 

lobster_abundance <- read_csv(here::here("data", "lobster_abundance.csv"), 
                              na = "-99999") %>% 
  clean_names()
  
```

Use the tidyr::uncount() function to expand a frequency variable (lobster count)

```{r}

lobster_tidy <- lobster_abundance %>% 
  tidyr::uncount(lobster_count)
```

Now each lobster has its own row, this is tidy format 

Let's look at the data in various visualizations 

```{r}
# Exploratory data visualization 

# Jitter plot 
ggplot(data = lobster_tidy, 
       aes(x = site, y = size_mm)) +
  geom_jitter(aes(color = site), 
              width = 0.2)

# Violin plot 
ggplot(data = lobster_tidy, 
       aes(x = site, y = size_mm)) +
  geom_violin(aes(color = site))

# Histogram 
ggplot(data = lobster_tidy, 
       aes(x = size_mm)) +
  geom_histogram (aes( fill = site)) +
  facet_wrap(~site, scale = "free") #function to separate histogram into each site, have scale adjust for each site (max and min for each group) 

# Quantile-quantile plot 
ggplot(data = lobster_tidy, 
       aes(sample = size_mm)) +
  geom_qq(size = 0.5) +
  facet_wrap(~site, scale = "free")

```

